[tool.black]
line-length = 100

[tool.isort]
profile = "black"
color_output = true
combine_as_imports = true
from_first = true
line_length = 100
known_first_party = ["internal_plugins"]

[tool.poetry.dev-dependencies]
Flake8-pyproject = "~1.2"
